/** Réexport du contrat — source de vérité : @hybridator/core-model */
export type {
  Asset,
  CatalogItem,
  CatalogKind,
  Clip,
  ClipAudio,
  ClipCrop,
  ClipMask,
  ClipMediaRole,
  ClipPatch,
  ClipTransform,
  ClipTransition,
  ColorGrade,
  EditOperation,
  EditorDoc,
  Effect,
  Keyframe,
  KeyframeTrack,
  NormalizedTranscript,
  ProjectSettings,
  SourceRange,
  Timeline,
  Track,
  TrackKind,
  TrackRole,
  TranscriptSegment,
  TranscriptWord,
} from "@hybridator/core-model";

export { ALL_TRACKS } from "@hybridator/core-model";
